### ISSUE TITLE
I would like to be able to use it with other launchers (such as MCLauncher).

### ISSUE THREAD

**Issue by Tensi1112** [FrederoxDev/Amethyst-Launcher#10]
I use BedrockLauncher to switch versions and manage save data.
Using this launcher downloads Minecraft to a different location than BedrockLauncher, which is not convenient for those using a different launcher.

Is there any way to make it possible to use AmethystRuntime even when using another MCBE launcher such as BedrockLauncher?

**Comment by ATXLtheAxolotl** [comment]
As of now you could manually transfer dxdgii.dll. In #9 I add support for using a custom directory however it still needs a few small adjustments before being accepted.
