### ISSUE TITLE
Unable to use the mods but can run the game.

### ISSUE THREAD

**Issue by Tlong21** [FrederoxDev/Amethyst-Launcher#11]
With both mods and the runtime installed in the mods folder Minecraft will instatly close out as soon as i hit launch game. I can only get it to run by deleting the launcher_config.json file but the mods do not load when I do that. Any support would be great! 1.73.1 version

**Comment by FrederoxDev** [comment]
What error are you getting? As a reminder we only support up to 1.20.71 so anything over that is likely to just not work.

**Comment by theaddonn** [comment]
pressing `ctrl` + `shift` + `i` opens the console, if you see any errors there - then please send them.

Also, 1.20.73.1 should work fine..  tested it

**Comment by Tlong21** [comment]
I download the game after importing the mods and launch it. On first launch the game loads and I can connect to my realm no issues but the mods did not load in. So Iclose my game and click launch game again in the launcher and then the CMD prompt starts and stops quickly, I get an popup error stating "Minecraft:" "The app didn't start." and nothing appears to be logged in the console for errors. Tried on multiple versions now all with the same issue.

**Comment by Tlong21** [comment]
Sometime this CMD prompt stays open "[AmethystProxy] Using 'AmethystProxy@1.0.0'
[AmethystProxy] McThreadID: 3204, McThreadHandle: 0x18c
[AmethystRuntime] McThreadID: 3204, McThreadHandle: 0x18c
[AmethystRuntime] Using 'AmethystRuntime@1.2.1'
[VidereLonge] Successfully loaded config.json from "C:\Users\Tyler\AppData\Local\Packages\microsoft.minecraftuwp_8wekyb3d8bbwe\AC/Amethyst/mods/VidereLonge@1.1.1/config.json"
[AmethystRuntime] Loading 'BetterInventory@1.5.1'
[AmethystRuntime] Loading 'VidereLonge@1.1.1'
[AmethystRuntime] Exception thrown at 0x87ea41b8e in C:\Users\Tyler\AppData\Roaming\Amethyst\versions\Minecraft-1.20.73.1\Minecraft.Windows.exe. Exception code: 0xc0000005
Press Numpad0 to close..."

**Comment by theaddonn** [comment]
maybe try launching without VidereLonge or BetterInventory
