### ISSUE TITLE
Versions manager in launcher

### ISSUE THREAD

**Issue by CornetPanique86** [FrederoxDev/Amethyst-Launcher#14]
Have the ability to see which versions are installed and downloaded and be able to delete them to save space. Could be in the settings menu or a new page.
Otherwise you could make a "Open versions folder" in settings

**Comment by shiftier** [comment]
it should show in the launcher settings as "Install Path"
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/79581780/a55b667b-d10b-400c-a313-828236037052)

**Comment by OmniacDev** [comment]
Added in #46
