### ISSUE TITLE
Old mod versions reappear in temp folder and profiles.json

### ISSUE THREAD

**Issue by Tallis-Larsen** [FrederoxDev/Amethyst-Launcher#15]
For the time being, I am unaware why this issue occurs, and unable to recreate it

- When launching the game, an error along the lines of "cannot locate modpackname.dll" occurs
- This is because an empty folder for an older version of the mod exists inside the Amethyst/temp folder
- When launching, a non-existent DLL file is searched for, but not found, leading to an error
- When this empty folder is deleted, a new one reappears immediately after attempting to launch again
- The profiles.json file shows this empty folder mod in the list of activated mods for a given profile
- This mod is not shown as active in the profile GUI
- This is why the launcher is looking for a mod that does not exist; it thinks you have selected it to be active in your profile
- When the mod name is deleted from the profiles.json file, it reappears just like the empty folder does
- Temporary solution: Delete the faulty profile and create a new one

I tried to be as clear as possible in this bug report, but if something doesn't make sense or information is missing, I can try my best to clarify

**Comment by FrederoxDev** [comment]
pretty sure this is fixed? Feel free to re-open
