### ISSUE TITLE
Cannot do anything except launching Minecraft

### ISSUE THREAD

**Issue by tungdo0602** [FrederoxDev/Amethyst-Launcher#16]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/89498812/0e576f75-341d-4a4f-a235-2b87ab0a564a)
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/89498812/da4cf0c4-be9c-457f-ab7a-6a1da50e106f)
Mod not load also although I've put it in correct folder

**Comment by FrederoxDev** [comment]
1.20.71 was deleted by mojang, it can't be downloaded. Most mods will work on .72, but we don't support it officially.

**Comment by theaddonn** [comment]
did you select the amethyst runtime and the mods you want to play in the profile?

**Comment by FrederoxDev** [comment]
> did you select the amethyst runtime and the mods you want to play in the profile?
> 
> 

See my above comment.

**Comment by tungdo0602** [comment]
> 1.20.71 was deleted by mojang, it can't be downloaded. Most mods will work on .72, but we don't support it officially.

oh ok

**Comment by tungdo0602** [comment]
> did you select the amethyst runtime and the mods you want to play in the profile?

actually I don't see any tab that related to mod

**Comment by theaddonn** [comment]
the furnace icon opens the profile page, there click on your created profile or create a new one
then simpley select your runtime version and the mods you want to play.. like shown here:
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/127942625/66fee676-92ed-4e29-88c0-0880b699df65)
 
 You will probably be using other mods than in the screenshot and also another runtime version, if the runtime is `Vanilla` you get the normal Minecraft without amethyst.

**Comment by tungdo0602** [comment]
> the furnace icon opens the profile page, there click on your created profile or create a new one then simpley select your runtime version and the mods you want to play.. like shown here: ![image](https://private-user-images.githubusercontent.com/127942625/330843460-66fee676-92ed-4e29-88c0-0880b699df65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODQwOTgsIm5iZiI6MTcxNTc4Mzc5OCwicGF0aCI6Ii8xMjc5NDI2MjUvMzMwODQzNDYwLTY2ZmVlNjc2LTkyZWQtNGUyOS04OGMwLTA4ODBiNjk5ZGY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDM2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmQ4MGZjMDZjZWRhNjRmM2VhNDNiMzc0MTA0ODBkN2E4YjFmNDJjOGM2MjU5MTg4YmRlNDQ0Njg0MDE1YTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IBB340vMspYyk8oNEI3ra5dX7IRBv0IEvyOXU0wIE8s)
> 
> You will probably be using other mods than in the screenshot and also another runtime version, if the runtime is `Vanilla` you get the normal Minecraft without amethyst.

How can I both install vanilla minecraft and use the mod because your launcher download so slow :(

**Comment by tungdo0602** [comment]
so I need to switch to mc win 10 launcher

**Comment by tungdo0602** [comment]
> the furnace icon opens the profile page, there click on your created profile or create a new one then simpley select your runtime version and the mods you want to play.. like shown here: ![image](https://private-user-images.githubusercontent.com/127942625/330843460-66fee676-92ed-4e29-88c0-0880b699df65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODQwOTgsIm5iZiI6MTcxNTc4Mzc5OCwicGF0aCI6Ii8xMjc5NDI2MjUvMzMwODQzNDYwLTY2ZmVlNjc2LTkyZWQtNGUyOS04OGMwLTA4ODBiNjk5ZGY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDM2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmQ4MGZjMDZjZWRhNjRmM2VhNDNiMzc0MTA0ODBkN2E4YjFmNDJjOGM2MjU5MTg4YmRlNDQ0Njg0MDE1YTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IBB340vMspYyk8oNEI3ra5dX7IRBv0IEvyOXU0wIE8s)
> 
> You will probably be using other mods than in the screenshot and also another runtime version, if the runtime is `Vanilla` you get the normal Minecraft without amethyst.

also when select 1.20.72 I only saw Vanilla runtime

**Comment by theaddonn** [comment]
did you downlaod the rutime from github and put it unzipped in the mods folder?

**Comment by theaddonn** [comment]
> How can I both install vanilla minecraft and use the mod because your launcher download so slow :(

You can create multiple profiles, for example one with vanilla 1.20.81 and one with amethyst 1.20.72.
also after you downloaded the versions switching to a new profile is relatively fast

**Comment by tungdo0602** [comment]
> did you downlaod the rutime from github and put it unzipped in the mods folder?

Oh I only put there and forgot to unzip it xD

**Comment by tungdo0602** [comment]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/89498812/a4a10ad4-0970-4c60-8022-d4ae86a4b6b9)
It seemed that it doesn't register the package for me how do I fix it?

**Comment by tungdo0602** [comment]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/89498812/4c5030e6-d287-4433-9d45-8562feed995b)
When I tried manual registering I got this error

**Comment by FrederoxDev** [comment]
Enable developer mode in the windows settings to run that command

**Comment by tungdo0602** [comment]
> Enable developer mode in the windows settings to run that command

I already did that.

**Comment by FrederoxDev** [comment]
The command output says otherwise XD

Try doing a restart then running again to give the shell an opportunity to refresh

**Comment by tungdo0602** [comment]
> The command output says otherwise XD
> 
> Try doing a restart then running again to give the shell an opportunity to refresh

still didn't work :(

**Comment by olivi-r** [comment]
> ![image](https://private-user-images.githubusercontent.com/89498812/330852620-4c5030e6-d287-4433-9d45-8562feed995b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NTQxMTQsIm5iZiI6MTcxNjg1MzgxNCwicGF0aCI6Ii84OTQ5ODgxMi8zMzA4NTI2MjAtNGM1MDMwZTYtZDI4Ny00NDMzLTlkNDUtODU2MmZlZWQ5OTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIzNTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NzI3NTJhNDE2ZmMzZjVjNTg1NDI4Njk1ZmM1NmJkZTIzMWRkMmNlZWZjYjE0ZThjZTJlNjA2YjU5MTZlN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDPLdx6pH3xaq1-KA5Yn-7hFKkhIA4359FZhHhA21V4) When I tried manual registering I got this error

Based on the screenshot provided, it looks like the package is still signed, try deleting or renaming `AppxSignature.p7x`

**Comment by FrederoxDev** [comment]
You're not in windows S mode or anything that would be denying sideloaded apps?

**Comment by tungdo0602** [comment]
yes

> You're not in windows S mode or anything that would be denying sideloaded apps?
