### ISSUE TITLE
Load mods from `.mcmod` files

### ISSUE THREAD

**Issue by theaddonn** [FrederoxDev/Amethyst-Launcher#17]
It would be awesome if we could load mods from simple `.mcmod` files that when double clicked open the launcher and provide an ui to select a profile that the given mod should be added to (including copying it to the mods folder/providing a custom installation directory for it like mentioned in this pr https://github.com/FrederoxDev/Amethyst-Launcher/pull/9)

(`.mcmod` is not the final extension, we should still discuss it)

**Comment by outercloudstudio** [comment]
What about an extension like `.amethyst`?

**Comment by Adrian8115** [comment]
we could probably make a discord poll for that...

**Comment by FrederoxDev** [comment]
I like .amethyst

**Comment by OmniacDev** [comment]
`.amethyst` is a bit long, maybe something like `.amth`

**Comment by jLn0n** [comment]
just as what I've said in https://github.com/FrederoxDev/Amethyst/issues/81#issuecomment-2131128802, `.mcamod`

**Comment by FrederoxDev** [comment]
I think im pretty happy with `.amethyst`. We aren't Minecraft and shouldn't be using their prefixes.

**Comment by jLn0n** [comment]
> I think im pretty happy with `.amethyst`. We aren't Minecraft and shouldn't be using their prefixes.

to make it shorter, `.amod` :trollface:

**Comment by FrederoxDev** [comment]
I don't think shorter is something i care about. `.amethyst` is very explicit, whereas `.amod` you have to make a decisive leap to conclude its standing for amethyst mod
