### ISSUE TITLE
Feat: Android Port?

### ISSUE THREAD

**Issue by MikaelaMuller** [FrederoxDev/Amethyst-Launcher#31]
Feature request: Amethyst Launcher Android port. 

Reason: I'm making an assumption that Amethyst launcher is capable of allowing for optimization mods so having this on handheld devices would be great.

**Comment by FrederoxDev** [comment]
Mobile devices run on different architectures and platforms to our regular target windows. This isn't about the launcher, it's the runtimes and mods that would have to be specialized which would require a lot of time investment.

**Comment by theaddonn** [comment]
This launcher ia for windows only, an android app will very likely be a completly different codebase. If you want to further request a mobile port, then just create an issue on the main repository. 
Also, yes.. optimization mods are possible
