### ISSUE TITLE
App crash when changing theme while unzipping versiom

### ISSUE THREAD

**Issue by jeanmajid** [FrederoxDev/Amethyst-Launcher#37]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/124172979/4719ec1e-62b2-4864-ad00-79ef82a4bcf5)
![IMG_5176](https://github.com/FrederoxDev/Amethyst-Launcher/assets/124172979/a5a1e798-880b-464f-b98d-78361cd5e45c)

**Comment by jeanmajid** [comment]
Update: each time I try to newly open it it at first shows the regular screen and then goes to black screen

**Comment by theaddonn** [comment]
Update: reinstall doesn't help

**Comment by FrederoxDev** [comment]
This crash should be fixed by https://github.com/FrederoxDev/Amethyst-Launcher/commit/aba9fdc5a1a3dab0b6a2c09361011a8e3fd01b30

**Comment by FrederoxDev** [comment]
Closing for now, if issue persists, feel free to reopen
