### ISSUE TITLE
Stuck registering download version

### ISSUE THREAD

**Issue by yeah-Im-liam** [FrederoxDev/Amethyst-Launcher#38]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/82614333/8a830b1d-6181-4d42-ba33-d7f2885ea6e2)
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/82614333/7cbe3ec8-011b-4a0c-bf95-d4e79a058023)
tried uninstalling the profile and reinstalling, not sure what to do here

**Comment by FrederoxDev** [comment]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/69014593/6d1370ce-3c10-4a4e-a24a-ee788049c588)

**Comment by yeah-Im-liam** [comment]
👍
