### ISSUE TITLE
Loding profile stuck at "Registering download version"

### ISSUE THREAD

**Issue by TabFox-log** [FrederoxDev/Amethyst-Launcher#42]
Version of Launcher: 2.4.7
Game Version: 1.21.0.3 Vanilla, unmodded
Never launched the game from this lancher, first time ever. It's just stuck at Registering version

**Comment by FrederoxDev** [comment]
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/69014593/52e396cb-d32d-4002-a3d1-c2b42247d5a4)

**Comment by TabFox-log** [comment]
ok

**Comment by TabFox-log** [comment]
Instructions clear.
Issue corrected with a successful result.

**Comment by Ahmedkhan981** [comment]
please create a video for error please

**Comment by OmniacDev** [comment]
> please create a video for error please

huh? why?

**Comment by FrederoxDev** [comment]
> please create a video for error please

This is already a solved issue

**Comment by Ahmedkhan981** [comment]
First, I uninstalled my Minecraft Bedrock Edition from Windows. Then, I installed the Amethyst Launcher. After creating a profile and clicking the start button, all necessary downloads began. This process corrected any mistakes and improved the overall experience.
![Screenshot 2024-07-28 150237](https://github.com/user-attachments/assets/31492579-35de-4a4e-abd9-7f7392573fda)
![Screenshot 2024-07-28 150216](https://github.com/user-attachments/assets/8a0bdab7-00b8-4369-bed7-4ea468d5de16)

**Comment by Ahmedkhan981** [comment]
Now, please tell me what to do next.

**Comment by OmniacDev** [comment]
Usually it says that if you don't own Minecraft Bedrock through Microsoft Store, in which case, you can't use Amethyst Launcher.

**Comment by OmniacDev** [comment]
Uninstalling is also no longer needed, it should work by itself.

**Comment by Ahmedkhan981** [comment]
Thank you for your apply. Does this mean Amethyst Launcher will start working automatically?
