### ISSUE TITLE
Automatically detect failing to register and prompt user to manually backup and uninstall

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst-Launcher#43]
Related: https://github.com/FrederoxDev/Amethyst-Launcher/issues/42

**Comment by OmniacDev** [comment]
Issue fixed in #46

**Comment by OmniacDev** [comment]
This issue can be closed, the original problem with unregistering failing has been solved in the latest launcher version.

**Comment by OmniacDev** [comment]
OK I really don't know how, but I forgot to actually change the file in #46 even though I put the fix in the commit message.

It's now properly fixed in #51
