### ISSUE TITLE
Error after trying to start game

### ISSUE THREAD

**Issue by theaddonn** [FrederoxDev/Amethyst-Launcher#5]
Hello, I am a purple potato,

I've compiled Amethyst api & runtime for 1.2.0 and also the new Launcher

After trying to start the game, for version 1.20.51.1 with the runtime included, I got this error in the launcher's console:
```
Currently installed packageId undefined
node:fs:1229 Uncaught (in promise) Error: EBUSY: resource busy or locked, rmdir '\\?\C:\Users\i_dont_give_my_name_to_windows\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\AC\Amethyst\mods\AmethystRuntime@1.2.0'
    at rmdirSync (node:fs:1229:10)
    at _rmdirSync (node:internal/fs/rimraf:235:5)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
``` 

I have the Runtime in a folder called AmethystRuntime@1.2.0

There is the compiled runtime dll + it's pdb and the mod.json

which is as following:
```json
{
  "meta": {
    "name": "AmethystRuntime",
    "version": "1.2.0",
    "author": "FederoxDev",
    "is_runtime": true
  },
  "dependencies": []
}
```

The launcher is also now stuck on "Restoring existing Minecraft data", no lauchner.json is in the amethyst folder anymore and the dll, pdb and mod.json are all gone in the folder

The progressbar is also stuck on being grey and nothing happens...

Help would be appreciated, thx

**Comment by FrederoxDev** [comment]
Should be fixed in the new release? lmk

**Comment by theaddonn** [comment]
I think?
after bit everything suddenlly worked?

idk
