### ISSUE TITLE
Registration Possibly Failing

### ISSUE THREAD

**Issue by OmniacDev** [FrederoxDev/Amethyst-Launcher#52]
It seems that something do with registering the new version is failing. 

I'm currently looking into this, but a bit more information would be helpful.

Cases:
1. ~~https://github.com/FrederoxDev/Amethyst/issues/118~~ (Resolved)
2. ~~https://discord.com/channels/1184966397864980601/1261704727368962098~~ (Fixed)

**Comment by OmniacDev** [comment]
@YaghoobMB Open the Developer Console using `Ctrl + Shift + i` and send a screenshot of what it says after you try to launch.

**Comment by OmniacDev** [comment]
Issue 2 in [discord](https://discord.com/channels/1184966397864980601/1261704727368962098) is fixed

**Comment by YaghoobMB** [comment]
![Screenshot (66)](https://github.com/user-attachments/assets/257d1e5f-1e5d-40ab-9731-d83739a802d4)
 
thanks to bedrock launcher i got minecraft back this time
what does it mean "unregistering existing version"?

**Comment by YaghoobMB** [comment]
![Uploading Screenshot (70).png…]()
thanks to bedrock launcher i got minecraft back this time
what does it mean "unregistering existing version"?

**Comment by YaghoobMB** [comment]
thanks to bedrock launcher i got minecraft back this time
what does it mean "unregistering existing version"?
![Screenshot (70)](https://github.com/user-attachments/assets/5a39dbea-0c24-4ba5-96c0-48dfa5f51132)

**Comment by OmniacDev** [comment]
It's part of the process of using custom versions. Unregistering removes the old version from the window's registry, (tells windows not to use that version), and then we register our version, which adds it to the registry (tells windows to use that version when launching).

**Comment by OmniacDev** [comment]
It doesn't look like there's any errors in that screenshot. Was it still not working when you did that?

**Comment by YaghoobMB** [comment]
this will pop up
![Screenshot (69)](https://github.com/user-attachments/assets/0c6a95b1-12bd-43ed-ae59-7b845beb6cf6)

**Comment by OmniacDev** [comment]
Do you own Minecraft from the Microsoft Store?

**Comment by YaghoobMB** [comment]
no 
maybe
idk how it works

**Comment by OmniacDev** [comment]
You don't own Minecraft Bedrock?

**Comment by YaghoobMB** [comment]
minecraft.net says i do
 but let's not go into details 😂

**Comment by OmniacDev** [comment]
Well we sort of do need the details because the launcher will only work if you do own it

**Comment by YaghoobMB** [comment]
why every thing has to be so complicated?
if i want to download a game i have to change my ip 
i have to use a dns to join minecraft servers 
i cant buy a game manually because of boycott
man, Microsoft even doesn't support my country
this is what i did:
i connected to my vpn and downloaded minecraft for windows free trail then i changed some files 
now i access to minecraft bedrock edition
you're telling me that amethyst doesn't work like that ?

**Comment by OmniacDev** [comment]
Yeah sorry amethyst doesn't work with that. It says it in the readme, you gotta own Minecraft Bedrock for it to work. (at least with the launcher. you could try manually copying the proxy over but that's complicated)

**Comment by YaghoobMB** [comment]
Sorry for any trouble I may have caused

**Comment by OmniacDev** [comment]
Nah it's all good
