### ISSUE TITLE
Amethyst Launcher replaces Bedrock Launcher installation

### ISSUE THREAD

**Issue by NaKeRNarolino** [FrederoxDev/Amethyst-Launcher#7]
**Steps to reproduce:**

1.Install "Latest Release" from Bedrock launcher
2.Install 1.20.51 from Amethyst Launcher

**_Even when starting from Bedrock Launcher it launches 1.20.51_**

**Comment by FrederoxDev** [comment]
We don't support external launchers officially, this is not a bug

**Comment by NaKeRNarolino** [comment]
Ok
